#!/usr/bin/env python3
"""Generate EC-V preconfiguration YAML for the Greek fabric, one per appliance.

WHY PRECONFIGS
--------------
A preconfig is staged on Orchestrator BEFORE an appliance registers and is
matched by hostname tag as it comes up, so the EC-V self-configures on first
contact instead of needing a second pass. Deployment profiles are a largely
dead concept in current Orchestrator; preconfig is the supported path.

WHERE THE SCHEMA CAME FROM
--------------------------
Not guesswork - `GET /gms/appliance/preconfiguration/default` returns a fully
commented 3500-line template documenting every section. Fetch it again if
anything here stops validating:

    GET https://<orch>/gms/rest/gms/appliance/preconfiguration/default
    -> {"configData": "<base64 YAML>"}

Three things that are easy to get wrong and cost a round trip each:

  * WAN interfaces that use DHCP need `addressingMode: dhcpv4` with
    `ipAddressMask:` and `nextHop:` left EMPTY. Writing `ipAddressMask: dhcp`
    is rejected.
  * The field is `behindNat` (lowercase "at"), even though the template's own
    comment block spells it `behindNAT`. The comment is wrong; the parser is
    not.
  * `interfaceLabel` must be a label NAME that already exists in Orchestrator
    (GET /gms/interfaceLabels), not an id. Ours: wan INET1/INET2, lan Data.

ALWAYS validate before pushing - the endpoint tells you exactly which field is
wrong, which is how this schema was mapped in the first place:

    POST /gms/appliance/preconfiguration/validate {name, configData}

INTERFACE ROLES (mirrors the working S1-ecv-01 deployment)
    lan0 -> bd-01 ge-0/0/3      static /31, appliance takes .1
    lan1 -> bd-02 ge-0/0/3      static /31, appliance takes .1
    wan0 -> isp-a (Internet)    DHCP from the site's own dnsmasq
    wan1 -> isp-b (MPLS)        DHCP from the site's own dnsmasq

    python3 scripts/gen_ecv_preconfigs.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "preconfigs")

# site -> (prefix, host-subnet second octet). The second octet is the site
# index, same value the topology generator uses for 10.<idx>.10.0/24.
SITES = {
    "thermopylae": ("TH", 5),
    "troy":        ("TR", 6),
    "marathon":    ("MA", 7),
}

BANDWIDTH = 1000000          # kbps, matches the EC-V's licensed capacity
LAN_LABEL = "Data"
WAN0_LABEL = "INET1"         # isp-a / Internet
WAN1_LABEL = "INET2"         # isp-b / MPLS

TEMPLATE = """\
# {site_upper} {ecv} - EC-V preconfiguration
#
# GENERATED by scripts/gen_ecv_preconfigs.py - edit the generator, not this file.
#
# Schema is from GET /gms/appliance/preconfiguration/default. Validate any change
# with POST /gms/appliance/preconfiguration/validate before pushing; it names the
# offending field, which is far faster than reading the 3500-line template.
#
# lan0/lan1 are static /31s to the two border switches. wan0/wan1 take DHCP from
# this site's own isp-a / isp-b routers, so they carry no static addressing:
# addressingMode dhcpv4 REQUIRES ipAddressMask and nextHop to be empty.
applianceInfo:
  hostname: {ecv}
  networkRole: non-hub
deploymentInfo:
  deploymentMode: inline-router
  totalOutboundBandwidth: {bw}
  totalInboundBandwidth: {bw}
  deploymentInterfaces:
    - interfaceName: lan0
      interfaceLabel: {lan_label}
      interfaceType: lan
      interfaceComment: to {prefix}-vjunos-bd-01 ge-0/0/{p1}
      ipAddressMask: {lan0}/31
    - interfaceName: lan1
      interfaceLabel: {lan_label}
      interfaceType: lan
      interfaceComment: to {prefix}-vjunos-bd-02 ge-0/0/{p1}
      ipAddressMask: {lan1}/31
    - interfaceName: wan0
      interfaceLabel: {wan0_label}
      interfaceType: wan
      interfaceComment: isp-a Internet transport
      addressingMode: dhcpv4
      ipAddressMask:
      nextHop:
      outboundMaxBandwidth: {bw}
      inboundMaxBandwidth: {bw}
      firewallMode: statefulSNAT
      behindNat: auto
    - interfaceName: wan1
      interfaceLabel: {wan1_label}
      interfaceType: wan
      interfaceComment: isp-b MPLS transport
      addressingMode: dhcpv4
      ipAddressMask:
      nextHop:
      outboundMaxBandwidth: {bw}
      inboundMaxBandwidth: {bw}
      firewallMode: statefulSNAT
      behindNat: auto
"""


def build(site, num):
    prefix, idx = SITES[site]
    ecv = "%s-ecv-%02d" % (prefix, num)
    # ecv-01 takes 10.<idx>.0.1 / 10.<idx>.1.1, ecv-02 takes .2.1 / .3.1 -
    # distinct /31s per appliance per border switch, no overlap between the pair.
    base = (num - 1) * 2
    return ecv, TEMPLATE.format(
        site_upper=site.upper(), ecv=ecv, prefix=prefix, bw=BANDWIDTH,
        lan_label=LAN_LABEL, wan0_label=WAN0_LABEL, wan1_label=WAN1_LABEL,
        lan0="10.%d.%d.1" % (idx, base),
        lan1="10.%d.%d.1" % (idx, base + 1),
        p1=3 if num == 1 else 4)


def main():
    os.makedirs(OUT, exist_ok=True)
    for site in SITES:
        for num in (1, 2):
            ecv, body = build(site, num)
            path = os.path.join(OUT, "%s.yml" % ecv)
            with open(path, "w") as fh:
                fh.write(body)
            print("wrote %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
